from __future__ import annotations

TRACK_LENGTH_M = 101.0
TRACK_WIDTH_M = 1.2

LONG_CUT_PRICE_PER_M = 460.0
TRANSVERSE_CUT_PRICE = 1200.0
WEIGHT_KG_PER_DM2 = 2.83333333

DEFAULT_MANAGER_ROLE = "manager"
DEFAULT_PRODUCTION_ROLE = "production"
DEFAULT_ADMIN_ROLE = "admin"

